### ISSUE TITLE
FR: Open Multiple Files

### ISSUE THREAD

**Issue by ghost** [SimplGy/obsidian-open-file-by-magic-date#2] opened 2023-03-04 15:39 UTC
I just wanted to say that your Open File by Magic Date plugin for Obsidian is fantastic! It's been an absolute lifesaver in my note-taking workflow, and I really appreciate the effort you've put into creating such a useful tool.

I was wondering if it would be possible to add a functionality that allows us to open multiple files with date patterns in their file names simultaneously? It would be a huge time-saver for me and I'm sure many others would find it useful as well.

Thank you again for all your hard work on this plugin, and I'm excited to see what future developments you have in store.

**Comment by SimplGy** [comment] 2023-03-04 20:11
Thanks for the nice comment.

Can you give me an example of specifically what pattern you would use, and what files you would want it to open?

**Comment by SimplGy** [comment] 2023-03-04 20:22
Probably pretty tricky though. The [main API I use](https://github.com/SimplGy/obsidian-open-file-by-magic-date/blob/master/src/main.ts#L109) opens by file name, not pattern. I don't think there's a search API provided, although I do wish there were.

https://marcus.se.net/obsidian-plugin-docs/reference/typescript/classes/Vault

**Comment by ghost** [comment] 2023-03-04 23:35
> Thanks for the nice comment.
> 
> Can you give me an example of specifically what pattern you would use, and what files you would want it to open?

Thank you for your quick response! Here are the files I would want to open with their corresponding patterns:

- Main/Daily/2023-03-03.md (YYYY-MM-DD)
- Main/Learned/Learned 2023-03-03.md (YYYY-MM-DD)
- Main/Journal/Journal 2023-03-03.md (YYYY-MM-DD)
- Main/Logs/Log 2023-03-03.md (YYYY-MM-DD)
- Main/Work/Work 2023-03-03.md (YYYY-MM-DD)

I hope this information helps! Thank you for considering my feature request.

**Comment by SimplGy** [comment] 2023-03-12 22:45
Distinct from #3 I think because this is asking to open several files with one command, where #3 is asking to open different files with different commands.

**Comment by khldgit** [comment] 2023-03-14 11:06
I apologize for any confusion. To clarify, my request is to open those files using distinct commands for each file.

**Comment by ghost** [comment] 2023-03-14 11:20
I'm sorry for the mistake in my previous comment. Including the word 'simultaneously' did not accurately describe my request. What I actually meant was to open different files using distinct commands for each file, instead of opening multiple files at the same time. I hope this clarifies my intention."

**Comment by SimplGy** [comment] 2023-03-15 04:15
No problem, just a dupe of #3 -- that's good though, it means 100% of the customers I've heard from want this feature :)

**Closed as not planned by SimplGy** 2023-03-15 04:15 UTC
